<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	  <AkkaVersion>1.5.40</AkkaVersion>
	  <AkkaHostingVersion>1.5.38</AkkaHostingVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
	  <PackageVersion Include="Akka.Persistence.Query" Version="$(AkkaVersion)" />
	  <PackageVersion Include="Azure.Data.Tables" Version="12.10.0" />
	  <PackageVersion Include="Azure.Identity" Version="1.13.2" />
	  <PackageVersion Include="Azure.Storage.Blobs" Version="12.23.0" />
	  <PackageVersion Include="System.Linq.Async" Version="6.0.1" />
	  <PackageVersion Include="Akka.Persistence.Hosting" Version="$(AkkaHostingVersion)" />
	  <PackageVersion Include="Akka.Cluster.Hosting" Version="$(AkkaHostingVersion)" />
  </ItemGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Akka.Cluster.Sharding" Version="$(AkkaVersion)" />
	  <PackageVersion Include="NBench" Version="2.0.1" />
	  <PackageVersion Include="Docker.DotNet" Version="3.125.15" />
	  <PackageVersion Include="Akka.Persistence.TCK" Version="$(AkkaVersion)" />
	  <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4"/>
    <PackageVersion Include="PublicApiGenerator" Version="9.3.0" />
    <PackageVersion Include="Verify.Xunit" Version="25.0.2" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.0.0" />
	  <PackageVersion Include="xunit" Version="2.8.1" />
	  <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>