<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AkkaVersion>1.5.59</AkkaVersion>
    <AkkaHostingVersion>1.5.59</AkkaHostingVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka.Persistence.Query" Version="$(AkkaVersion)" />
    <PackageVersion Include="Azure.Data.Tables" Version="12.10.0" />
    <PackageVersion Include="Azure.Identity" Version="1.13.2" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.23.0" />
    <PackageVersion Include="System.Linq.Async" Version="6.0.1" />
    <PackageVersion Include="Akka.Persistence.Hosting" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="Akka.Cluster.Hosting" Version="$(AkkaHostingVersion)" />
    <!-- Needed to fix Microsoft.Identity.Client typosquatting phishing link bug (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5278) -->
    <PackageVersion Include="Microsoft.Identity.Client" Version="4.73.1" />
    <PackageVersion Include="Testcontainers.Azurite" Version="4.8.0" />
  </ItemGroup>
  <!-- Test dependencies -->
  <ItemGroup>
    <PackageVersion Include="Akka.Hosting.TestKit" Version="$(AkkaHostingVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageVersion Include="Akka.Cluster.Sharding" Version="$(AkkaVersion)" />
    <PackageVersion Include="NBench" Version="2.0.1" />
    <PackageVersion Include="Docker.DotNet" Version="3.125.15" />
    <PackageVersion Include="Akka.Persistence.TCK" Version="$(AkkaVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="PublicApiGenerator" Version="9.3.0" />
    <PackageVersion Include="Verify.Xunit" Version="25.0.2" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.0.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>
