<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
		<TargetFramework>$(NetVersion)</TargetFramework>
        <Description>Akka.Hosting support for Akka.Persistence.Azure.</Description>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Akka.Persistence.Azure\Akka.Persistence.Azure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Akka.Persistence.Hosting" />
    </ItemGroup>

</Project>
